### ISSUE TITLE
Source code of schemaCompile

### ISSUE THREAD

**Issue by yoursunny** [pollere/DCT#1]
Source code of [schemaCompile](https://github.com/pollere/DCT/blob/3c7780faa45142e97f9bbabff2eed78502b53a15/versec/linux-schemaCompile-bin-1.0.1.tgz) is missing.
Please upload source code to comply with GPL requirements.

**Comment by kmnichols** [comment]
schemaCompile binaries are not GPL'd and contain no GPL code. Relocated the binaries to the releases page to avoid confusion with the license for open source files in the same directory.
