### ISSUE TITLE
sigmgrs: timing attack vulnerability

### ISSUE THREAD

**Issue by yoursunny** [pollere/DCT#6]
`SigMgrRFC7693::validate` and `SigMgrSHA256::validate` functions verify BLAKE2b or SHA256 signature.
Each function first creates a correct BLAKE2b or SHA256 signature over the input, then compares the incoming signature with that correct signature.
The comparison step is coded as:

https://github.com/pollere/DCT/blob/cdf4c89e6908b697005df5b905c8b84d46793a08/include/dct/sigmgrs/sigmgr_rfc7693.hpp#L85-L91
https://github.com/pollere/DCT/blob/cdf4c89e6908b697005df5b905c8b84d46793a08/include/dct/sigmgrs/sigmgr_sha256.hpp#L85

The `std::memcmp` function returns as soon as finding the first different element.
As a result, these functions are vulnerable to timing attacks because the execution time of these function leaks the information about which is the first byte that differs from the correct signature.

To fix this bug, use a [constant-time comparison function](https://github.com/veorq/cryptocoding/tree/cdd3f56106f57893922190b0f56c934d9d0f6fd5#compare-secret-strings-in-constant-time) such as [sodium\_memcmp](https://doc.libsodium.org/helpers#constant-time-test-for-equality).

**Comment by kmnichols** [comment]
The vulnerability associated with using std::memcmp that we are aware of [citation] applies to crypo text not to data integrity checking as in our signature managers that use SHA256 and the RFC7693 algorithms. The sodium memcmp always takes constant (i.e., worst case) time. Hence use of that function here would impair performance with no gain in security so we do not use it here.
